import { supabaseUsinagem, loadUsinagem } from '../services/usinagem-service.mjs';

const app = document.getElementById('app');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const fmt = value => Number(value || 0).toLocaleString('pt-BR', { maximumFractionDigits: 1 });
const hours = rows => rows.reduce((sum, row) => sum + (new Date(row.fim) - new Date(row.inicio)) / 3600000, 0);
function bars(items, suffix = '') { if (!items.length) return '<p class="state">Sem dados no período.</p>'; const max = items[0].total || 1; return items.slice(0, 8).map(item => `<div class="bar"><span>${esc(item.name)}</span><i style="width:${Math.max(2, item.total / max * 100)}%"></i><b>${fmt(item.total)}${suffix}</b></div>`).join(''); }
function view(data) {
  const totals = data.totals; const good = totals.reduce((s, x) => s + x.good, 0); const scrap = totals.reduce((s, x) => s + x.scrap, 0); const productive = totals.reduce((s, x) => s + x.hours, 0); const stops = data.stopsHours;
  const unitCards = totals.map(x => `<article class="card"><small>Produção líquida · ${esc(x.unit)}</small><strong>${fmt(x.good)}</strong></article>`).join('');
  const byReason = [...data.validStops.reduce((map, row) => { const key = row.motivo || row.tipo || row.classificacao || 'Não informado'; map.set(key, (map.get(key) || 0) + (new Date(row.fim) - new Date(row.inicio)) / 3600000); return map; }, new Map())].map(([name,total]) => ({name,total})).sort((a,b)=>b.total-a.total);
  app.innerHTML = `<header><div><h1>🏭 Usinagem</h1><div class="stamp">Indicadores operacionais · últimos 7 dias</div></div><div class="stamp">Atualizado ${new Date().toLocaleTimeString('pt-BR')}</div></header><section class="grid">${unitCards}<article class="card"><small>Produtividade válida</small><strong>${totals.map(x => `${fmt(x.productivity)} ${esc(x.unit)}/h`).join(' · ') || '—'}</strong></article><article class="card"><small>Refugo</small><strong>${totals.map(x => `${fmt(x.scrapRate)}% ${esc(x.unit)}`).join(' · ') || '—'}</strong></article><article class="card"><small>Tempo de parada</small><strong>${fmt(stops)} h</strong></article><article class="card"><small>Tempo produtivo</small><strong>${fmt(productive)} h</strong></article><article class="card"><small>Apontamentos</small><strong>${fmt(data.scoped.length)}</strong></article></section><section class="panels"><article class="card"><h2>Produção por máquina</h2>${bars(data.groups.maquina)}</article><article class="card"><h2>Pareto de paradas</h2>${bars(byReason, ' h')}</article></section>`;
}
async function configure() { if (supabaseUsinagem.configured) return true; try { const response = await fetch('../api/usinagem-config', { cache:'no-store' }); if (!response.ok) return false; const config = await response.json(); if (config?.configured) supabaseUsinagem.configure(config); } catch {} return supabaseUsinagem.configured; }
async function refresh() { if (!await configure()) { app.innerHTML = '<p class="state">Fonte de dados da Usinagem ainda não configurada.</p>'; return; } try { const now = new Date(); view(await loadUsinagem({ from: new Date(now.getTime() - 7 * 24 * 3600000), to: now })); } catch (error) { app.innerHTML = `<p class="state">${esc(error.message || 'Não foi possível carregar os indicadores.')}</p>`; } }
refresh(); setInterval(refresh, 60000);
